#!/usr/bin/env python3
"""Generate polished, stable SVG cards for a GitHub profile README.

The README references generated files in ./assets so profile rendering does not
rely on third-party dynamic image services.
"""

from __future__ import annotations

import json
import os
import pathlib
import time
import urllib.error
import urllib.parse
import urllib.request
from html import escape
from typing import Any

USERNAME = os.getenv("GITHUB_USERNAME") or os.getenv("GITHUB_REPOSITORY_OWNER") or "songs66"
TOKEN = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")
OUTPUT_DIR = pathlib.Path(os.getenv("OUTPUT_DIR", "assets"))
API_ROOT = "https://api.github.com"

HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "profile-readme-stats-generator",
}
if TOKEN:
    HEADERS["Authorization"] = f"Bearer {TOKEN}"

THEME = {
    "bg_1": "#050b16",
    "bg_2": "#0d1117",
    "bg_3": "#111827",
    "panel": "#0f172a",
    "panel_2": "#111c2e",
    "border": "#30363d",
    "border_soft": "#1f6feb",
    "title": "#e6edf3",
    "accent": "#58a6ff",
    "accent_2": "#d2a8ff",
    "accent_3": "#7ee787",
    "text": "#c9d1d9",
    "muted": "#8b949e",
    "bar_bg": "#21262d",
}

LANG_COLORS = [
    "#58a6ff",
    "#f78166",
    "#d2a8ff",
    "#7ee787",
    "#ffdf5d",
    "#ffa657",
    "#a5d6ff",
    "#79c0ff",
]

FONT = "Segoe UI, Inter, Helvetica, Arial, sans-serif"


def request_json(url: str) -> Any:
    request = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def paginated(url: str) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    separator = "&" if "?" in url else "?"
    page = 1
    while True:
        page_url = f"{url}{separator}per_page=100&page={page}"
        batch = request_json(page_url)
        if not isinstance(batch, list):
            break
        items.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return items


def format_number(value: int) -> str:
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"{value / 1_000:.1f}k"
    return str(value)


def format_bytes(value: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    amount = float(value)
    index = 0
    while amount >= 1024 and index < len(units) - 1:
        amount /= 1024
        index += 1
    if index == 0:
        return f"{int(amount)} {units[index]}"
    return f"{amount:.1f} {units[index]}"


def svg_shell(width: int, height: int, title: str, body: str) -> str:
    return f'''<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">{escape(title)}</title>
  <desc id="desc">Self-hosted GitHub profile statistics card generated by GitHub Actions.</desc>
  <defs>
    <linearGradient id="card-bg" x1="0" y1="0" x2="430" y2="190" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="{THEME['bg_1']}"/>
      <stop offset="0.55" stop-color="{THEME['bg_2']}"/>
      <stop offset="1" stop-color="{THEME['bg_3']}"/>
    </linearGradient>
    <linearGradient id="border-grad" x1="0" y1="0" x2="430" y2="190" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="{THEME['accent']}" stop-opacity="0.75"/>
      <stop offset="0.45" stop-color="{THEME['border']}" stop-opacity="0.9"/>
      <stop offset="1" stop-color="{THEME['accent_2']}" stop-opacity="0.75"/>
    </linearGradient>
    <linearGradient id="accent-grad" x1="24" y1="0" x2="406" y2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="{THEME['accent']}"/>
      <stop offset="0.55" stop-color="{THEME['accent_2']}"/>
      <stop offset="1" stop-color="{THEME['accent_3']}"/>
    </linearGradient>
    <filter id="soft-shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="8" stdDeviation="9" flood-color="#000000" flood-opacity="0.28"/>
    </filter>
    <filter id="blur-glow" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur stdDeviation="22"/>
    </filter>
  </defs>
  <rect x="0.75" y="0.75" width="428.5" height="188.5" rx="16" fill="url(#card-bg)" stroke="url(#border-grad)" stroke-width="1.5"/>
  <circle cx="370" cy="26" r="54" fill="{THEME['accent']}" opacity="0.13" filter="url(#blur-glow)"/>
  <circle cx="62" cy="171" r="46" fill="{THEME['accent_2']}" opacity="0.10" filter="url(#blur-glow)"/>
  <path d="M24 49 H406" stroke="url(#accent-grad)" stroke-width="1" opacity="0.55"/>
  {body}
</svg>
'''


def pill(x: int, y: int, text: str, width: int, fill: str = "#111c2e") -> str:
    return f'''<rect x="{x}" y="{y}" width="{width}" height="22" rx="11" fill="{fill}" stroke="{THEME['border']}" opacity="0.95"/>
  <text x="{x + width / 2:.1f}" y="{y + 15}" fill="{THEME['muted']}" font-family="{FONT}" font-size="11" font-weight="600" text-anchor="middle">{escape(text)}</text>'''


def metric_card(x: int, y: int, width: int, label: str, value: str, color: str) -> str:
    return f'''<g filter="url(#soft-shadow)">
    <rect x="{x}" y="{y}" width="{width}" height="43" rx="12" fill="{THEME['panel']}" stroke="{THEME['border']}" opacity="0.94"/>
    <circle cx="{x + 17}" cy="{y + 16}" r="5" fill="{color}" opacity="0.95"/>
    <text x="{x + 30}" y="{y + 18}" fill="{THEME['muted']}" font-family="{FONT}" font-size="11" font-weight="600">{escape(label)}</text>
    <text x="{x + 30}" y="{y + 35}" fill="{THEME['title']}" font-family="{FONT}" font-size="18" font-weight="800">{escape(value)}</text>
  </g>'''


def stats_card(username: str, repos: list[dict[str, Any]], languages: dict[str, int]) -> str:
    non_forks = [repo for repo in repos if not repo.get("fork")]
    stars = sum(int(repo.get("stargazers_count") or 0) for repo in non_forks)
    forks = sum(int(repo.get("forks_count") or 0) for repo in non_forks)
    main_language = max(languages, key=languages.get) if languages else "N/A"
    language_count = len(languages)
    code_size = format_bytes(sum(languages.values())) if languages else "N/A"
    updated_at = time.strftime("%Y-%m-%d", time.gmtime())

    body = f'''
  <text x="24" y="28" fill="{THEME['title']}" font-family="{FONT}" font-size="18" font-weight="800">{escape(username)} · GitHub</text>
  <text x="24" y="43" fill="{THEME['muted']}" font-family="{FONT}" font-size="11">Profile metrics generated as stable SVG</text>
  {pill(300, 17, "AUTO UPDATED", 106)}
  {metric_card(24, 63, 178, "Repositories", format_number(len(non_forks)), LANG_COLORS[0])}
  {metric_card(228, 63, 178, "Stars", format_number(stars), LANG_COLORS[4])}
  {metric_card(24, 116, 178, "Forks", format_number(forks), LANG_COLORS[1])}
  {metric_card(228, 116, 178, "Languages", format_number(language_count), LANG_COLORS[3])}
  <rect x="24" y="169" width="382" height="1" fill="url(#accent-grad)" opacity="0.50"/>
  <text x="24" y="182" fill="{THEME['muted']}" font-family="{FONT}" font-size="10">Primary: <tspan fill="{THEME['accent']}" font-weight="700">{escape(main_language)}</tspan> · Code size: {escape(code_size)}</text>
  <text x="406" y="182" fill="{THEME['muted']}" font-family="{FONT}" font-size="10" text-anchor="end">{updated_at}</text>
'''
    return svg_shell(430, 190, f"{username}'s GitHub Stats", body)


def top_languages_card(languages: dict[str, int]) -> str:
    total = sum(languages.values())
    top = sorted(languages.items(), key=lambda item: item[1], reverse=True)[:6]

    if not top or total <= 0:
        body = f'''
  <text x="24" y="28" fill="{THEME['title']}" font-family="{FONT}" font-size="18" font-weight="800">Top Languages</text>
  <text x="24" y="43" fill="{THEME['muted']}" font-family="{FONT}" font-size="11">No language data available yet</text>
'''
        return svg_shell(430, 190, "Top Languages", body)

    segments = []
    cursor = 24.0
    bar_width = 382.0
    for index, (_, bytes_count) in enumerate(top):
        width = max(3.0, bar_width * bytes_count / total)
        color = LANG_COLORS[index % len(LANG_COLORS)]
        segments.append(f'<rect x="{cursor:.1f}" y="59" width="{width:.1f}" height="10" rx="5" fill="{color}"/>')
        cursor += width

    rows = []
    y = 91
    for index, (language, bytes_count) in enumerate(top):
        percent = bytes_count / total * 100
        color = LANG_COLORS[index % len(LANG_COLORS)]
        bar = max(3, int(190 * percent / 100))
        rows.append(f'''
  <circle cx="31" cy="{y - 4}" r="4" fill="{color}"/>
  <text x="43" y="{y}" fill="{THEME['text']}" font-family="{FONT}" font-size="12" font-weight="700">{escape(language)}</text>
  <rect x="150" y="{y - 9}" width="190" height="7" rx="3.5" fill="{THEME['bar_bg']}" opacity="0.95"/>
  <rect x="150" y="{y - 9}" width="{bar}" height="7" rx="3.5" fill="{color}"/>
  <text x="386" y="{y}" fill="{THEME['muted']}" font-family="{FONT}" font-size="11" font-weight="600" text-anchor="end">{percent:.1f}%</text>''')
        y += 15

    body = f'''
  <text x="24" y="28" fill="{THEME['title']}" font-family="{FONT}" font-size="18" font-weight="800">Top Languages</text>
  <text x="24" y="43" fill="{THEME['muted']}" font-family="{FONT}" font-size="11">Weighted by repository language bytes</text>
  {pill(319, 17, f"{len(languages)} LANGS", 87)}
  <rect x="24" y="59" width="382" height="10" rx="5" fill="{THEME['bar_bg']}" opacity="0.9"/>
  {''.join(segments)}
  {''.join(rows)}
'''
    return svg_shell(430, 190, "Top Languages", body)


def collect_data(username: str) -> tuple[list[dict[str, Any]], dict[str, int]]:
    encoded = urllib.parse.quote(username)
    repos = paginated(f"{API_ROOT}/users/{encoded}/repos?type=owner&sort=updated")
    repos = [repo for repo in repos if not repo.get("archived")]

    languages: dict[str, int] = {}
    for repo in repos:
        if repo.get("fork"):
            continue
        full_name = repo.get("full_name")
        if not full_name:
            continue
        url = f"{API_ROOT}/repos/{urllib.parse.quote(full_name, safe='/')}/languages"
        try:
            repo_languages = request_json(url)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError):
            continue
        if not isinstance(repo_languages, dict):
            continue
        for language, byte_count in repo_languages.items():
            languages[language] = languages.get(language, 0) + int(byte_count)
    return repos, languages


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    repos, languages = collect_data(USERNAME)
    (OUTPUT_DIR / "github-stats.svg").write_text(stats_card(USERNAME, repos, languages), encoding="utf-8")
    (OUTPUT_DIR / "top-langs.svg").write_text(top_languages_card(languages), encoding="utf-8")


if __name__ == "__main__":
    main()
